### ISSUE TITLE
Can't install v3 on forge

### ISSUE THREAD

**Issue by antoniopgs** [paulrberg/prb-math#147]
After running: `forge install --no-commit paulrberg/prb-math@v3`, I get:
![image](https://user-images.githubusercontent.com/44982443/206257802-e0ea231f-636f-4a27-bb9c-6d73c6a6dc0b.png)

Also tried:
- `forge install https://github.com/paulrberg/prb-math@v3` (same error)
- `forge install https://github.com/paulrberg/prb-math@v3.0.0` (same error)
![image](https://user-images.githubusercontent.com/44982443/206259557-8292d93a-7d2d-4d8b-b140-c6fc6da1f50a.png)

Also re-tried all 3 options after a `forge clean`. Didn't work either.
![image](https://user-images.githubusercontent.com/44982443/206259924-0d7432cb-eb17-45b2-97c3-bc412b729a5d.png)

Finally, updated my foundry via `foundryup`. Currently running `forge 0.2.0 (427c1b5 2022-12-07T00:09:22.004732Z)`.
Still didn't fix it.

**Comment by paulrberg** [comment]
Thanks for reporting this, @antoniopgs. Dependency management is an area that is unfortunately still not great in Foundry.

This is odd. I just ran the two commands you have run on my machine, and they both worked fine:

<img width="1207" alt="Screenshot 2022-12-07 at 9 38 38 PM" src="https://user-images.githubusercontent.com/8782666/206279182-f18e94d3-c15d-4387-9324-53b298db6db7.png">

So I cannot reproduce this. Might you be able to share the following information?

- OS version
- git version
- forge version

In the meantime, a couple of notes:

- It is confusing that Foundry refers to the value after the `@` as the "tag", because that value can be a branch, tag, or commit, not just a tag. A better term to use in this console log would be "ref" (I'm considering opening an issue about this in the Foundry repo)
- `.gitmodules` doesn't support git tags, so it's best to use branches to prevent accidentally upgrading to the latest commit of a git repo (without a `branch` entry in your `.gitmodules`, git modules will be upgraded to the latest `main` or `master` whenever you run `git submodule update --remote`)
- You actually don't need to to specify a "tag" (i.e. `@v3`) for Forge to be able to install a dependency. So maybe this works: `forge install paulrberg/prb-math`?
- The context in which you are running the command might also play a role here. Have you tried installing PRBMath in a copy of my [Foundry template](https://github.com/paulrberg/foundry-template)?

**Comment by andreivladbrg** [comment]
Should be a local issue @antoniopgs. 

For me works perfectly fine:
<img width="1494" alt="Screenshot 2022-12-08 at 5 09 34 PM" src="https://user-images.githubusercontent.com/99738872/206482392-62f4c144-8184-4502-acc9-b1e7ea4ccab9.png">

**Comment by antoniopgs** [comment]
updated MacOS to Ventura, and now it works

**Comment by antoniopgs** [comment]
![image](https://user-images.githubusercontent.com/44982443/206539563-f01f0826-69d5-431e-be25-f54e43316d54.png)

I'm just doing `import ./Math.sol`
Why is it looking for `Math.sol` in `lib/prb-math/src` instead of the current folder?

**Comment by antoniopgs** [comment]
nevermind, the problem was the auto inferred remappings. turned them off and it fixed it.

**Comment by paulrberg** [comment]
Thanks for reporting the solutions, @antoniopgs. I'm glad that it works now.

**Comment by nolanjannotta** [comment]
@antoniopgs I am running into the same issue, how do you turn off auto inferred remappings?

**Comment by antoniopgs** [comment]
From the Foundry Docs:
https://book.getfoundry.sh/reference/config/solidity-compiler?highlight=auto_detect_remappings#general
<img width="1396" alt="Screenshot 2023-02-17 at 11 07 09" src="https://user-images.githubusercontent.com/44982443/219601416-188300bf-f88e-4484-8a15-303f55e7c8a3.png">

So just add this to your `foundry.toml`:
<img width="559" alt="Screenshot 2023-02-17 at 11 05 52" src="https://user-images.githubusercontent.com/44982443/219601527-24ac3d83-d4e5-4c37-aaf8-203e5d83b886.png">

**Comment by nolanjannotta** [comment]
awesome, thank you!

**Comment by PaulRBerg** [comment]
Thanks for your question, @nolanjannotta, and thanks for chiming in to help, @antoniopgs!

I just wanted to add that this is a known bug upstream in Foundry, which I hope will get patched in the near future.

https://github.com/foundry-rs/foundry/issues/3440

If this doesn't get fixed in Foundry, I might have to drop the [`src/=src/`](https://github.com/PaulRBerg/prb-math/blob/4213ccd29a4bfcf6a413848448ec611b7c97f346/remappings.txt#L3) remapping and use relative imports in the PRBMath tests.
