### ISSUE TITLE
Member "ln" not found or not visible after argument-dependent lookup in type(SD59x18).

### ISSUE THREAD

**Issue by Noctemn** [PaulRBerg/prb-math#164]
When I do this 
```SD59x18 something = SD59x18.ln(SD59x18.wrap(int256(2)));```
The console says e 
```TypeError: Member "ln" not found or not visible after argument-dependent lookup in type(SD59x18).```
Other functions such as ```wrap``` and ```div``` are working just fine. 
When I checked the sd59x18 library, the linter complains about ``` assembly ("memory-safe") { ``` for ```extraneous input '(' expecting {'{', StringLiteralFragment} [undefined]".``` Nothing changes if I replace that with just ```assembly {```

Seems to something off?

**Comment by PaulRBerg** [comment]
> `SD59x18 something = SD59x18.ln(SD59x18.wrap(int256(2)));`

It is not possible to use the functions defined in user-defined value types in this way.

The correct way is to access the functions by using the dot operator, like this:

```solidity
SD59x18 x = SD59x18.wrap(2);
SD59x18 something = x.ln();
```

Alternatively, you could also import the `ln` function, like this:

```solidity
import { ln } from "@prb/math/sd59x18/Math.sol";

SD59x18 x = SD59x18.wrap(2);
SD59x18 something = ln(x);
```

Finally, note that you can make the typecasting look prettier (more succinct) using the `sd` casting utility:

```solidity
import { sd } from "@prb/math/SD59x18.sol";

SD59x18 x = sd(2);
SD59x18 something = x.ln();
```

> Other functions such as `wrap` and `div` are working just fine.

`wrap` works because that's a built-in function compiler. `div` doesn't work, so I'm not sure how you got it working. This code does not compile:

```solidity
SD59x18 x = SD59x18.wrap(2);
result = SD59x18.div(x, x);
```

> the linter complains about `assembly ("memory-safe")`

That is not an issue with the linter but with the VSCode Solidity extension:

https://github.com/juanfranblanco/vscode-solidity/issues/386
