### ISSUE TITLE
Backport `Fix bit mask in Common.exp2 function` to v3.3.*

### ISSUE THREAD

**Issue by frontier159** [PaulRBerg/prb-math#198]
### What version of PRBMath are you using?

v3.3.2

### What version of Solidity are you using?

v0.8.18

### Operating System

None

### Describe the bug

A bit mask bug was fixed in exp2(), in https://github.com/PaulRBerg/prb-math/pull/179 

Given this resulted in a High Risk finding in: https://github.com/zobront/audits/blob/main/reports/sablier-1.pdf
could we also fix in the v3.3.* releases as a patch? 

v4 requires an upgrade to solc v0.8.19 which isn't easily possible for all cases.
Also [slither still recommends v0.8.18](https://github.com/crytic/slither/wiki/Detector-Documentation#recommendation-74)

**Comment by frontier159** [comment]
I'd be happy to raise PR if you let me know the best branch to target 🙏

**Comment by PaulRBerg** [comment]
Hi @frontier159, thanks for opening this issue. I'd be happy to accept a PR that backports the fix for `Common.exp2`. You can target the `release-v3` branch.

Side note: I highly recommend upgrading to V4 for getting all the improvements mentioned in the [changelog](https://github.com/PaulRBerg/prb-math/blob/main/CHANGELOG.md).

Slither's recommended version will always lag behind the most recent versions of Solidity, but they will eventually bump the pragma. Tagging @0xalpharush in case he could lend us a hand here and upgrade the minimum pragma recommended by Slither to `0.8.19`.

**Comment by frontier159** [comment]
I'm going to close in favour of upgrading to the audited v4.0.1. Will take the hit to update solc
